dniLista: list[str] = []
apellidoLista: list[str] = []
nombreLista: list[str] = []
edadLista: list[str] = []  # or list[int] if you convert to integers
fechaDeNacimientoLista: list[str] = []
profesionLista: list[str] = []
montoLista: list[str] = []  # or list[float] if you convert to floats
fechaDeclararLista: list[str] = []
origenLista: list[str] = []
bienesArgentinasLista: list[bool] = []
bienesExterioresLista: list[bool] = []